// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: measurements.sql

package measurements

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateMeasurementParams struct {
	ComponentID  pgtype.Int4 `json:"component_id"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        pgtype.Int4 `json:"pet_id"`
	Amount       float32     `json:"amount"`
}
