// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pets_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :exec
INSERT INTO pets (name, birth, passport, chip)
VALUES ($1, $2, $3, $4)
`

type CreatePetParams struct {
	Name     string      `json:"name"`
	Birth    pgtype.Date `json:"birth"`
	Passport pgtype.Text `json:"passport"`
	Chip     pgtype.Text `json:"chip"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) error {
	_, err := q.db.Exec(ctx, createPet,
		arg.Name,
		arg.Birth,
		arg.Passport,
		arg.Chip,
	)
	return err
}

const createWeightMeasure = `-- name: CreateWeightMeasure :exec
INSERT INTO pet_weight (weight, date_measured, pet_id)
VALUES ($1, $2, $3)
`

type CreateWeightMeasureParams struct {
	Weight       float32     `json:"weight"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        int32       `json:"pet_id"`
}

func (q *Queries) CreateWeightMeasure(ctx context.Context, arg CreateWeightMeasureParams) error {
	_, err := q.db.Exec(ctx, createWeightMeasure, arg.Weight, arg.DateMeasured, arg.PetID)
	return err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePet, id)
	return err
}

const getPet = `-- name: GetPet :one
SELECT id, name, birth, passport, chip FROM pets WHERE id = $1
`

func (q *Queries) GetPet(ctx context.Context, id int32) (Pet, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Birth,
		&i.Passport,
		&i.Chip,
	)
	return i, err
}

const removeWeightMeasure = `-- name: RemoveWeightMeasure :exec
DELETE FROM pet_weight 
WHERE pet_id = $1 AND date_measured = $2
`

type RemoveWeightMeasureParams struct {
	PetID        int32       `json:"pet_id"`
	DateMeasured pgtype.Date `json:"date_measured"`
}

func (q *Queries) RemoveWeightMeasure(ctx context.Context, arg RemoveWeightMeasureParams) error {
	_, err := q.db.Exec(ctx, removeWeightMeasure, arg.PetID, arg.DateMeasured)
	return err
}

const updatePet = `-- name: UpdatePet :exec
UPDATE pets SET 
    name = coalesce($1, name), 
    birth = coalesce($2, birth), 
    passport = coalesce($3, passport), 
    chip = coalesce($4, chip)
WHERE id = $5
`

type UpdatePetParams struct {
	Name     string      `json:"name"`
	Birth    pgtype.Date `json:"birth"`
	Passport pgtype.Text `json:"passport"`
	Chip     pgtype.Text `json:"chip"`
	ID       int32       `json:"id"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) error {
	_, err := q.db.Exec(ctx, updatePet,
		arg.Name,
		arg.Birth,
		arg.Passport,
		arg.Chip,
		arg.ID,
	)
	return err
}
