// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: measurement_unit.sql

package measurement_unit

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO measurement_unit (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) Create(ctx context.Context, name string) (MeasurementUnit, error) {
	row := q.db.QueryRow(ctx, create, name)
	var i MeasurementUnit
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM measurement_unit
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT id, name
FROM measurement_unit
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (MeasurementUnit, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i MeasurementUnit
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT id, name
FROM measurement_unit
`

func (q *Queries) GetMany(ctx context.Context) ([]MeasurementUnit, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeasurementUnit
	for rows.Next() {
		var i MeasurementUnit
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateByID = `-- name: UpdateByID :one
UPDATE measurement_unit
SET name = $1
WHERE id = $2
RETURNING id, name
`

type UpdateByIDParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateByID(ctx context.Context, arg UpdateByIDParams) (MeasurementUnit, error) {
	row := q.db.QueryRow(ctx, updateByID, arg.Name, arg.ID)
	var i MeasurementUnit
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
