CREATE TABLE pets (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    birth date,
    passport text,
    chip text
);

CREATE TABLE pet_weight (
    id integer PRIMARY KEY generated by default as identity,
    weight real NOT NULL,
    date_measured date NOT NULL default CURRENT_DATE,
    pet_id integer NOT NULL references pets (id)
);

CREATE TABLE panel_measurement_units (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL
);

CREATE TABLE panel_components (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    unit_id integer references panel_measurement_units (id),
    min_amount real,
    max_amount real,
    comment text
);

CREATE TABLE panel_measurements (
    id integer PRIMARY KEY generated by default as identity,
    component_id integer references panel_components (id),
    date_measured date NOT NULL,
    pet_id integer references pets (id),
    amount real NOT NULL
);
