CREATE TABLE pet (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    birth date,
    passport text,
    chip text
);

CREATE TABLE pet_weight (
    id integer PRIMARY KEY generated by default as identity,
    weight real NOT NULL,
    date_measured date NOT NULL default CURRENT_DATE,
    pet_id integer NOT NULL references pet (id)
);

CREATE TABLE measurement_unit (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL
);

CREATE TABLE component (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    unit_id integer references measurement_unit (id),
    min_amount real,
    max_amount real,
    comment text
);

CREATE TABLE panel (
    id integer PRIMARY KEY generated by default as identity,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE panel_component (
    id integer PRIMARY KEY generated by default as identity,
    panel_id integer references panel (id),
    pet_id integer references pet (id),
    component_id integer references component (id),
    date_measured date NOT NULL,
    value real NOT NULL
);
