// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: component.sql

package component

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO component (name, unit_id, min_amount, max_amount, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateParams struct {
	Name      string        `json:"name"`
	UnitID    pgtype.Int4   `json:"unit_id"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.UnitID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Comment,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM component
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT component.id,
	   component.name,
	   measurement_unit.name AS unit,
	   min_amount,
	   max_amount,
	   comment
FROM component
JOIN measurement_unit ON component.unit_id = measurement_unit.id
WHERE component.id = $1
`

type GetByIDRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Unit      string        `json:"unit"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) GetByID(ctx context.Context, id int32) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.MinAmount,
		&i.MaxAmount,
		&i.Comment,
	)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT component.id,
	   component.name,
	   measurement_unit.name AS unit,
	   min_amount,
	   max_amount,
	   comment
FROM component
JOIN measurement_unit ON component.unit_id = measurement_unit.id
`

type GetManyRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Unit      string        `json:"unit"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) GetMany(ctx context.Context) ([]GetManyRow, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManyRow
	for rows.Next() {
		var i GetManyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.MinAmount,
			&i.MaxAmount,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateByID = `-- name: UpdateByID :one
UPDATE component
SET name = coalesce($2, name),
    unit_id = coalesce($3, unit_id),
    min_amount = coalesce($4, min_amount),
    max_amount = coalesce($5, max_amount),
    comment = coalesce($6, comment)
WHERE id = $1
RETURNING id, name, unit_id, min_amount, max_amount, comment
`

type UpdateByIDParams struct {
	ID        int32         `json:"id"`
	Name      pgtype.Text   `json:"name"`
	UnitID    pgtype.Int4   `json:"unit_id"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) UpdateByID(ctx context.Context, arg UpdateByIDParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateByID,
		arg.ID,
		arg.Name,
		arg.UnitID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Comment,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.MinAmount,
		&i.MaxAmount,
		&i.Comment,
	)
	return i, err
}
