// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package component

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Component struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	UnitID    pgtype.Int4   `json:"unit_id"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}
