// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package panel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Panel struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
