// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: panel.sql

package panel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO panel (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Panel, error) {
	row := q.db.QueryRow(ctx, create, arg.Name, arg.Description)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM panel
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const getByID = `-- name: GetByID :one
SELECT panel.id,
       panel.name,
       panel.description,
       array_agg(
        json_build_object('id', component.id,
                          'name', component.name,
                          'description', component.description)) as components
FROM panel
JOIN panel_component ON panel.id = panel_component.panel_id
JOIN component ON panel_component.component_id = component.id
WHERE panel.id = $1
GROUP BY panel.id, panel.name, panel.description
`

type GetByIDRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Components  interface{} `json:"components"`
}

func (q *Queries) GetByID(ctx context.Context, id int32) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Components,
	)
	return i, err
}

const updateByID = `-- name: UpdateByID :one
UPDATE panel
SET name = coalesce($2, name),
    description = coalesce($3, description)
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateByIDParams struct {
	ID          int32       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateByID(ctx context.Context, arg UpdateByIDParams) (Panel, error) {
	row := q.db.QueryRow(ctx, updateByID, arg.ID, arg.Name, arg.Description)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
