// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: language.sql

package language

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO languages (name, label)
VALUES ($1, $2)
RETURNING id, name, label
`

type CreateParams struct {
	Name  string `json:"name"`
	Label string `json:"label"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Language, error) {
	row := q.db.QueryRow(ctx, create, arg.Name, arg.Label)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, name, label
FROM languages
`

func (q *Queries) GetAll(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.ID, &i.Name, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, name, label
FROM languages
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (Language, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}

const updateByID = `-- name: UpdateByID :one
UPDATE languages
SET name = coalesce($1, name),
    label = coalesce($2, label)
WHERE id = $3
RETURNING id, name, label
`

type UpdateByIDParams struct {
	Name  pgtype.Text `json:"name"`
	Label pgtype.Text `json:"label"`
	ID    int32       `json:"id"`
}

func (q *Queries) UpdateByID(ctx context.Context, arg UpdateByIDParams) (Language, error) {
	row := q.db.QueryRow(ctx, updateByID, arg.Name, arg.Label, arg.ID)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}
