// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: language.sql

package language

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (name, label)
VALUES ($1, $2)
RETURNING id, name, label
`

type CreateLanguageParams struct {
	Name  string `json:"name"`
	Label string `json:"label"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, arg.Name, arg.Label)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}

const getLanguagebyID = `-- name: GetLanguagebyID :one
SELECT id, name, label
FROM languages
WHERE id = $1
`

func (q *Queries) GetLanguagebyID(ctx context.Context, id int32) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguagebyID, id)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}

const getLanguages = `-- name: GetLanguages :many
SELECT id, name, label
FROM languages
`

func (q *Queries) GetLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, getLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.ID, &i.Name, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLanguage = `-- name: RemoveLanguage :exec
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) RemoveLanguage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeLanguage, id)
	return err
}
