// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package components

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Label string `json:"label"`
}

type PanelComponent struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	UnitID     pgtype.Int4 `json:"unit_id"`
	MinAmount  float32     `json:"min_amount"`
	MaxAmount  float32     `json:"max_amount"`
	Comment    pgtype.Text `json:"comment"`
	LanguageID pgtype.Int4 `json:"language_id"`
}

type PanelMeasurement struct {
	ID           int32       `json:"id"`
	ComponentID  pgtype.Int4 `json:"component_id"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        pgtype.Int4 `json:"pet_id"`
	Amount       float32     `json:"amount"`
}

type PanelMeasurementUnit struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	LanguageID pgtype.Int4 `json:"language_id"`
}

type Pet struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Birth    pgtype.Date `json:"birth"`
	Passport pgtype.Text `json:"passport"`
	Chip     pgtype.Text `json:"chip"`
}

type PetWeight struct {
	ID           int32       `json:"id"`
	Weight       float32     `json:"weight"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        int32       `json:"pet_id"`
}
