// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package panel_component

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PanelComponent struct {
	ID           int32       `json:"id"`
	PanelID      pgtype.Int4 `json:"panel_id"`
	PetID        pgtype.Int4 `json:"pet_id"`
	ComponentID  pgtype.Int4 `json:"component_id"`
	DateMeasured pgtype.Date `json:"date_measured"`
	Value        float32     `json:"value"`
}
