// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: languages.sql

package languages

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (name, label)
VALUES ($1, $2)
RETURNING id, name, label
`

type CreateLanguageParams struct {
	Name  string `json:"name"`
	Label string `json:"label"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRow(ctx, createLanguage, arg.Name, arg.Label)
	var i Language
	err := row.Scan(&i.ID, &i.Name, &i.Label)
	return i, err
}

const getLanguageID = `-- name: GetLanguageID :one
SELECT id
FROM languages
WHERE label = $1
`

func (q *Queries) GetLanguageID(ctx context.Context, label string) (int32, error) {
	row := q.db.QueryRow(ctx, getLanguageID, label)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLanguages = `-- name: GetLanguages :many
SELECT name
FROM languages
`

func (q *Queries) GetLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLanguage = `-- name: RemoveLanguage :exec
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) RemoveLanguage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeLanguage, id)
	return err
}
