// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: components.sql

package panel_components

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO panel_components (name, unit_id, min_amount, max_amount, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateParams struct {
	Name      string        `json:"name"`
	UnitID    pgtype.Int4   `json:"unit_id"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.UnitID,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Comment,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getMany = `-- name: GetMany :many
SELECT panel_components.id,
	   panel_components.name,
	   panel_measurement_units.name AS unit,
	   min_amount,
	   max_amount,
	   comment
FROM panel_components
JOIN panel_measurement_units ON panel_components.unit_id = panel_measurement_units.id
`

type GetManyRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Unit      string        `json:"unit"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) GetMany(ctx context.Context) ([]GetManyRow, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManyRow
	for rows.Next() {
		var i GetManyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.MinAmount,
			&i.MaxAmount,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOne = `-- name: GetOne :one
SELECT panel_components.id,
	   panel_components.name,
	   panel_measurement_units.name AS unit,
	   min_amount,
	   max_amount,
	   comment
FROM panel_components
JOIN panel_measurement_units ON panel_components.unit_id = panel_measurement_units.id
WHERE panel_components.id = $1
`

type GetOneRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Unit      string        `json:"unit"`
	MinAmount pgtype.Float4 `json:"min_amount"`
	MaxAmount pgtype.Float4 `json:"max_amount"`
	Comment   pgtype.Text   `json:"comment"`
}

func (q *Queries) GetOne(ctx context.Context, id int32) (GetOneRow, error) {
	row := q.db.QueryRow(ctx, getOne, id)
	var i GetOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.MinAmount,
		&i.MaxAmount,
		&i.Comment,
	)
	return i, err
}
