// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Label string `json:"label"`
}

type PanelComponent struct {
	ID            int32                        `json:"id"`
	Name          string                       `json:"name"`
	UnitID        pgtype.Int4                  `json:"unit_id"`
	AverageAmount pgtype.Range[pgtype.Numeric] `json:"average_amount"`
	Comment       pgtype.Text                  `json:"comment"`
	LanguageID    pgtype.Int4                  `json:"language_id"`
}

type PanelMeasurement struct {
	ID           int32       `json:"id"`
	ComponentID  pgtype.Int4 `json:"component_id"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        pgtype.Int4 `json:"pet_id"`
	Amount       float32     `json:"amount"`
}

type PanelUnit struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	LanguageID pgtype.Int4 `json:"language_id"`
}
