// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pet

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pet struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Birth    pgtype.Date `json:"birth"`
	Passport pgtype.Text `json:"passport"`
	Chip     pgtype.Text `json:"chip"`
}

type PetWeight struct {
	ID           int32       `json:"id"`
	Weight       float32     `json:"weight"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        int32       `json:"pet_id"`
}
