// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pet

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pet struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Birth    pgtype.Date `json:"birth"`
	Passport pgtype.Text `json:"passport"`
	Chip     pgtype.Text `json:"chip"`
}
