// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: weight.sql

package pet

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWeightMeasurement = `-- name: AddWeightMeasurement :one
INSERT INTO pet_weight (weight, date_measured, pet_id)
VALUES ($1, $2, $3)
RETURNING id, weight, date_measured, pet_id
`

type AddWeightMeasurementParams struct {
	Weight       float32     `json:"weight"`
	DateMeasured pgtype.Date `json:"date_measured"`
	PetID        int32       `json:"pet_id"`
}

func (q *Queries) AddWeightMeasurement(ctx context.Context, arg AddWeightMeasurementParams) (PetWeight, error) {
	row := q.db.QueryRow(ctx, addWeightMeasurement, arg.Weight, arg.DateMeasured, arg.PetID)
	var i PetWeight
	err := row.Scan(
		&i.ID,
		&i.Weight,
		&i.DateMeasured,
		&i.PetID,
	)
	return i, err
}

const deleteWeightMeasurement = `-- name: DeleteWeightMeasurement :exec
DELETE FROM pet_weight
WHERE id = $1
`

func (q *Queries) DeleteWeightMeasurement(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteWeightMeasurement, id)
	return err
}

const getManyWeightMeasurements = `-- name: GetManyWeightMeasurements :many
SELECT id, weight, date_measured, pet_id FROM pet_weight
WHERE pet_id = $1
`

func (q *Queries) GetManyWeightMeasurements(ctx context.Context, petID int32) ([]PetWeight, error) {
	rows, err := q.db.Query(ctx, getManyWeightMeasurements, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PetWeight
	for rows.Next() {
		var i PetWeight
		if err := rows.Scan(
			&i.ID,
			&i.Weight,
			&i.DateMeasured,
			&i.PetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
