CREATE TABLE pets (
    id integer PRIMARY KEY,
    name text NOT NULL,
    birth date,
    passport text,
    chip text
);

CREATE TABLE pet_weight (
    id integer PRIMARY KEY,
    weight real NOT NULL,
    date_measured date NOT NULL default CURRENT_DATE,
    pet_id integer NOT NULL
);

CREATE TABLE panel_measurement_units (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    language_id integer references languages (id)
);

CREATE TABLE panel_components (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    unit_id integer references panel_units (id),
    min_amount real not null,
    max_amount real not null,
    comment text,
    language_id integer references languages (id)
);

CREATE TABLE panel_measurements (
    id integer PRIMARY KEY generated by default as identity,
    component_id integer references panel_components (id),
    date_measured date NOT NULL,
    pet_id integer references pets (id),
    amount real NOT NULL
);

CREATE TABLE languages (
    id integer PRIMARY KEY generated by default as identity,
    name text NOT NULL,
    label text NOT NULL
);
